var stages = [
    {
        source: "coco",
        id: "seedling",
        name: "Seedling",
        phLow: 6.2,
        phHigh: 6.4,
        ppmTarget: 200,
        ECTarget: 400,
        products: [
            { id: "armorsi", amount: 0.0 },
            { id: "camg", amount: 4.0 },
            { id: "micro", amount: 1.25 },
            { id: "grow", amount: 0.6 },
            { id: "bloom", amount: 0.6 },
            { id: "koolbloom", amount: 0.0 },
            { id: "diamondnectar", amount: 2.5 },
            { id: "rapidstart", amount: 0.0 },
        ]
    },
    {
        source: "coco",
        id: "earlyveg",
        name: "Early Veg",
        phLow: 6.0,
        phHigh: 6.2,
        ppmTarget: 550,
        ECTarget: 1100,
        products: [
            { id: "armorsi", amount: 0.5 },
            { id: "camg", amount: 3.0 },
            { id: "micro", amount: 2.25 },
            { id: "grow", amount: 2.25 },
            { id: "bloom", amount: 0.6 },
            { id: "koolbloom", amount: 0.0 },
            { id: "diamondnectar", amount: 5.0 },
            { id: "rapidstart", amount: 2.0 },
        ]
    },

    {
        source: "coco",
        id: "midveg",
        name: "Mid Veg",
        phLow: 5.8,
        phHigh: 6.2,
        ppmTarget: 600,
        ECTarget: 1200,
        products: [
            { id: "armorsi", amount: 1.0 },
            { id: "camg", amount: 2.5 },
            { id: "micro", amount: 2.25 },
            { id: "grow", amount: 2.5 },
            { id: "bloom", amount: 1 },
            { id: "koolbloom", amount: 0.0 },
            { id: "diamondnectar", amount: 5.0 },
            { id: "rapidstart", amount: 2.0 },
        ]
    },
    {
        source: "coco",
        id: "lateveg",
        name: "Late Veg",
        phLow: 5.7,
        phHigh: 6.2,
        ppmTarget: 625,
        ECTarget: 1250,
        products: [
            { id: "armorsi", amount: 1.0 },
            { id: "camg", amount: 2.5 },
            { id: "micro", amount: 2.5 },
            { id: "grow", amount: 2.5 },
            { id: "bloom", amount: 1.2 },
            { id: "koolbloom", amount: 0.0 },
            { id: "diamondnectar", amount: 5.0 },
            { id: "rapidstart", amount: 1.0 },
        ]
    },






    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 1',
        name: 'Seedling',
        ppmTarget: 300,
        ppmTargetMax: 500,
        ECTarget: 0.6,
        ECTargetMax: 1,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 2.5 },
            { id: 'micro', amount: 2.5 },
            { id: 'bloom', amount: 2.5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 1',
        name: 'Seedling',
        ppmTarget: 400,
        ppmTargetMax: 600,
        ECTarget: 0.8,
        ECTargetMax: 1.2,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 2.5 },
            { id: 'micro', amount: 2.5 },
            { id: 'bloom', amount: 2.5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 10 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 1',
        name: 'Seedling',
        ppmTarget: 200,
        ppmTargetMax: 400,
        ECTarget: 0.4,
        ECTargetMax: 0.8,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 2 },
            { id: 'bloom', amount: 1 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 1',
        name: 'Seedling',
        ppmTarget: 200,
        ppmTargetMax: 400,
        ECTarget: 0.4,
        ECTargetMax: 0.8,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 2 },
            { id: 'bloom', amount: 1 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'diamondnectar', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 5 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 2',
        name: 'Early Growth',
        ppmTarget: 900,
        ppmTargetMax: 1100,
        ECTarget: 1.8,
        ECTargetMax: 2.2,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 10 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 2.5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 2',
        name: 'Early Growth',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 10 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 2.5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'diamondnectar', amount: 10 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 10 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 2',
        name: 'Early Growth',
        ppmTarget: 500,
        ppmTargetMax: 700,
        ECTarget: 1,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 5 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 1 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 2',
        name: 'Early Growth',
        ppmTarget: 600,
        ppmTargetMax: 700,
        ECTarget: 1.2,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 5 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 1 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 5 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 3',
        name: 'Late Growth',
        ppmTarget: 1000,
        ppmTargetMax: 1300,
        ECTarget: 2,
        ECTargetMax: 2.6,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 10 },
            { id: 'micro', amount: 10 },
            { id: 'bloom', amount: 5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 3',
        name: 'Late Growth',
        ppmTarget: 1200,
        ppmTargetMax: 1400,
        ECTarget: 2.4,
        ECTargetMax: 2.8,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 10 },
            { id: 'micro', amount: 10 },
            { id: 'bloom', amount: 5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'diamondnectar', amount: 10 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 10 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 3',
        name: 'Late Growth',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 5 },
            { id: 'micro', amount: 5 },
            { id: 'bloom', amount: 2.5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 3',
        name: 'Late Growth',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 5 },
            { id: 'micro', amount: 5 },
            { id: 'bloom', amount: 2.5 },
            { id: 'rapidstart', amount: 2.5 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 5 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 4',
        name: 'Transition',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 7.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 7.5 },
            { id: 'rapidstart', amount: 1 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 4',
        name: 'Transition',
        ppmTarget: 1100,
        ppmTargetMax: 1200,
        ECTarget: 2.2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 7.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 7.5 },
            { id: 'rapidstart', amount: 1 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 5 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 4',
        name: 'Transition',
        ppmTarget: 500,
        ppmTargetMax: 700,
        ECTarget: 1,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 4 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 4 },
            { id: 'rapidstart', amount: 1 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 4',
        name: 'Transition',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 1 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 4 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 4 },
            { id: 'rapidstart', amount: 1 },
            { id: 'diamondnectar', amount: 2.5 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 2.5 },
            { id: 'floranectar', amount: 2.5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 5',
        name: 'Early Bloom',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 10 },
            { id: 'rapidstart', amount: 1 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 5',
        name: 'Early Bloom',
        ppmTarget: 1100,
        ppmTargetMax: 1200,
        ECTarget: 2.2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 10 },
            { id: 'rapidstart', amount: 1 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 5 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 5',
        name: 'Early Bloom',
        ppmTarget: 500,
        ppmTargetMax: 700,
        ECTarget: 1,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 5 },
            { id: 'rapidstart', amount: 1 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 5',
        name: 'Early Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 5 },
            { id: 'rapidstart', amount: 1 },
            { id: 'diamondnectar', amount: 2.5 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 2.5 },
            { id: 'floranectar', amount: 2.5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 6',
        name: 'Early Bloom',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 10 },
            { id: 'rapidstart', amount: 1 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 6',
        name: 'Early Bloom',
        ppmTarget: 1100,
        ppmTargetMax: 1300,
        ECTarget: 2.2,
        ECTargetMax: 2.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 10 },
            { id: 'rapidstart', amount: 1 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 5 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 6',
        name: 'Early Bloom',
        ppmTarget: 500,
        ppmTargetMax: 700,
        ECTarget: 1,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 5 },
            { id: 'rapidstart', amount: 1 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 6',
        name: 'Early Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 5 },
            { id: 'rapidstart', amount: 1 },
            { id: 'diamondnectar', amount: 2.5 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 2.5 },
            { id: 'floranectar', amount: 2.5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 7',
        name: 'Mid Bloom',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 12.5 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 7',
        name: 'Mid Bloom',
        ppmTarget: 1100,
        ppmTargetMax: 1200,
        ECTarget: 2.2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 12.5 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 10 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 7',
        name: 'Mid Bloom',
        ppmTarget: 500,
        ppmTargetMax: 700,
        ECTarget: 1,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 6 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 7',
        name: 'Mid Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 6 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 2.5 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 8 ',
        name: 'Mid Bloom',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 12.5 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 8 ',
        name: 'Mid Bloom',
        ppmTarget: 1100,
        ppmTargetMax: 1200,
        ECTarget: 2.2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 2.5 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 12.5 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 5 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 10 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 8 ',
        name: 'Mid Bloom',
        ppmTarget: 500,
        ppmTargetMax: 700,
        ECTarget: 1,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 6 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 8 ',
        name: 'Mid Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 1 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 6 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 2.5 },
            { id: 'koolbloom', amount: 2 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 9',
        name: 'Late Bloom',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 0 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 15 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 9',
        name: 'Late Bloom',
        ppmTarget: 1200,
        ppmTargetMax: 1400,
        ECTarget: 2.4,
        ECTargetMax: 2.8,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 15 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 10 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 9',
        name: 'Late Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 8 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 9',
        name: 'Late Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 8 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 10',
        name: 'Late Bloom',
        ppmTarget: 1000,
        ppmTargetMax: 1200,
        ECTarget: 2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 0 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 15 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 10',
        name: 'Late Bloom',
        ppmTarget: 1200,
        ppmTargetMax: 1400,
        ECTarget: 2.4,
        ECTargetMax: 2.8,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 7.5 },
            { id: 'bloom', amount: 15 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 10 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 10',
        name: 'Late Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 8 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 10',
        name: 'Late Bloom',
        ppmTarget: 600,
        ppmTargetMax: 800,
        ECTarget: 1.2,
        ECTargetMax: 1.6,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 4 },
            { id: 'bloom', amount: 8 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 2.5 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 11 ',
        name: 'Ripen',
        ppmTarget: 800,
        ppmTargetMax: 1000,
        ECTarget: 1.6,
        ECTargetMax: 2,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'gro', amount: 0 },
            { id: 'micro', amount: 5 },
            { id: 'bloom', amount: 15 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 11 ',
        name: 'Ripen',
        ppmTarget: 1100,
        ppmTargetMax: 1200,
        ECTarget: 2.2,
        ECTargetMax: 2.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 5 },
            { id: 'bloom', amount: 15 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 10 },
            { id: 'koolbloom_dry', amount: 2.5 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 11 ',
        name: 'Ripen',
        ppmTarget: 400,
        ppmTargetMax: 600,
        ECTarget: 0.8,
        ECTargetMax: 1.2,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 2.5 },
            { id: 'bloom', amount: 8 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florakleen', amount: 0 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 11 ',
        name: 'Ripen',
        ppmTarget: 500,
        ppmTargetMax: 700,
        ECTarget: 1,
        ECTargetMax: 1.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 5 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 2.5 },
            { id: 'bloom', amount: 8 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 1 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 5 },
            { id: 'koolbloom_dry', amount: 2.5 },
            { id: 'florakleen', amount: 0 },
        ]
    },




    {
        source: 'ghe_recirc_simple',
        id: 'WEEK 12',
        name: 'Flush',
        ppmTarget: 0,
        ppmTargetMax: 200,
        ECTarget: 0,
        ECTargetMax: 0.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 0 },
            { id: 'gro', amount: 0 },
            { id: 'micro', amount: 0 },
            { id: 'bloom', amount: 0 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 0 },
            { id: 'florakleen', amount: 10 },
        ]
    },
    {
        source: 'ghe_recirc_expert',
        id: 'WEEK 12',
        name: 'Flush',
        ppmTarget: 0,
        ppmTargetMax: 200,
        ECTarget: 0,
        ECTargetMax: 0.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 0 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 0 },
            { id: 'bloom', amount: 0 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 0 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 10 },
        ]
    },
    {
        source: 'ghe_d2w_simple',
        id: 'WEEK 12',
        name: 'Flush',
        ppmTarget: 0,
        ppmTargetMax: 200,
        ECTarget: 0,
        ECTargetMax: 0.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 0 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 0 },
            { id: 'bloom', amount: 0 },
            { id: 'rapidstart', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 0 },
            { id: 'florakleen', amount: 10 },
        ]
    },
    {
        source: 'ghe_d2w_expert',
        id: 'WEEK 12',
        name: 'Flush',
        ppmTarget: 0,
        ppmTargetMax: 200,
        ECTarget: 0,
        ECTargetMax: 0.4,
        products: [
            { id: 'armorsi', amount: 0 },
            { id: 'calimagic', amount: 0 },
            { id: 'grow', amount: 0 },
            { id: 'micro', amount: 0 },
            { id: 'bloom', amount: 0 },
            { id: 'rapidstart', amount: 0 },
            { id: 'diamondnectar', amount: 0 },
            { id: 'koolbloom', amount: 0 },
            { id: 'floraliciousplus', amount: 0 },
            { id: 'florablend', amount: 0 },
            { id: 'floranectar', amount: 0 },
            { id: 'koolbloom_dry', amount: 0 },
            { id: 'florakleen', amount: 10 },
        ]
    },







];

